<#
.SYNOPSIS
    Register an hourly Windows scheduled task that captures the pre-deadline snapshot.

.DESCRIPTION
    `fpl snapshot --if-due` is a no-op unless a deadline is within the window and no
    pre-deadline snapshot is held for that gameweek, so running it hourly is cheap and
    idempotent. Hourly (rather than once a week) is deliberate: it survives a missed run,
    a reboot, and FPL moving a deadline.

    This matters because the snapshot is unrecoverable. Miss the GW1 deadline on
    2026-08-21 17:30 UTC and that state — injury news, prices, ownership — is gone.

.PARAMETER Checkpoints
    Hours before each deadline at which to capture, comma separated.
    Defaults to the module's ladder (48, 24, 6, 2, 0.5) — escalating captures so a later,
    better-informed snapshot supersedes an earlier one, and so a machine that is asleep
    for part of the run-up still gets several chances.

.PARAMETER TaskName
    Scheduled task name. Default "FPL Expert - deadline snapshot".

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File scripts\register_snapshot_task.ps1

.NOTES
    Registers a task under your own user account; no admin rights needed.
    Remove with:  Unregister-ScheduledTask -TaskName "FPL Expert - deadline snapshot"
#>
[CmdletBinding()]
param(
    [string] $Checkpoints = "",
    [string] $TaskName = "FPL Expert - deadline snapshot"
)

$ErrorActionPreference = "Stop"

$projectRoot = Split-Path -Parent $PSScriptRoot
$fpl = (Get-Command fpl -ErrorAction SilentlyContinue).Source
if (-not $fpl) {
    throw "'fpl' is not on PATH. Run 'pip install -e .' from $projectRoot first."
}

Write-Host "project : $projectRoot"
Write-Host "fpl     : $fpl"
if ($Checkpoints) { Write-Host "points  : $Checkpoints hours before each deadline" }
else { Write-Host "points  : default ladder (48, 24, 6, 2, 0.5 hours before each deadline)" }

$logDir = Join-Path $projectRoot "data\logs"
if (-not (Test-Path $logDir)) { New-Item -ItemType Directory -Path $logDir | Out-Null }

# Write a wrapper .cmd with the paths baked in, and point the task at that.
#
# Do NOT inline this as `cmd.exe /c "<exe>" ... >> "<log>" 2>&1`. When a /c command line
# begins with a quote, cmd strips the FIRST and LAST quote characters, which mangles any
# path containing spaces — here "...\Data Analytics\..." — and the task then fails with
# exit code 1 and an empty log, giving no clue why. A wrapper file has no nested quoting
# for cmd to misparse.
$logFile = Join-Path $logDir "snapshot.log"
$wrapper = Join-Path $PSScriptRoot "run_snapshot.cmd"
$cliArgs = "snapshot --if-due --reason scheduled"
if ($Checkpoints) { $cliArgs += " --checkpoints $Checkpoints" }

@(
    "@echo off",
    "rem Generated by register_snapshot_task.ps1 -- re-run that script to regenerate.",
    "`"$fpl`" $cliArgs >> `"$logFile`" 2>&1"
) | Set-Content -Path $wrapper -Encoding ASCII

$action = New-ScheduledTaskAction -Execute $wrapper -WorkingDirectory $projectRoot

# Hourly, indefinitely, starting on the next hour boundary.
$trigger = New-ScheduledTaskTrigger -Once -At (Get-Date).Date.AddHours((Get-Date).Hour + 1) `
    -RepetitionInterval (New-TimeSpan -Hours 1)

$settings = New-ScheduledTaskSettingsSet `
    -StartWhenAvailable `
    -DontStopOnIdleEnd `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 15) `
    -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 5)

if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
    Write-Host "replacing existing task '$TaskName'"
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
    -Settings $settings -Description "Captures FPL state before each gameweek deadline." | Out-Null

Write-Host ""
Write-Host "Registered '$TaskName' (hourly)." -ForegroundColor Green
Write-Host "  log      : $logFile"
Write-Host "  verify   : Get-ScheduledTask -TaskName `"$TaskName`""
Write-Host "  run now  : Start-ScheduledTask -TaskName `"$TaskName`""
Write-Host "  remove   : Unregister-ScheduledTask -TaskName `"$TaskName`""
