@echo off
rem Generated by register_snapshot_task.ps1 -- re-run that script to regenerate.
"C:\Users\Benedict\AppData\Local\Programs\Python\Python313\Scripts\fpl.exe" snapshot --if-due --reason scheduled >> "C:\Users\Benedict\OneDrive\Desktop\Data Analytics\Projects\FPL Expert\data\logs\snapshot.log" 2>&1
